BlogEntry:
  extensions:
    - "EnhancedBlogEntry"
  defaultGroup: 'content-authors'
BlogTree_Controller:
  extensions:
    - "BlogTreeControllerExtension"
Member:
  extensions:
    - "BlogAuthorMember"